services:
  postgres:
    container_name: aiblog-database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_DB=${PSQL_DATABASE}
    env_file:
      - .env